apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-code
data:
  app.py: |
    from flask import Flask, Response
    from prometheus_client import Counter, generate_latest, REGISTRY
    import time
    
    app = Flask(__name__)
    
    # Prometheus counter for tracking requests
    request_counter = Counter(
        'http_requests_total',
        'Total HTTP requests',
        ['service', 'endpoint']
    )
    
    @app.route('/')
    def index():
        request_counter.labels(service='frontend', endpoint='/').inc()
        time.sleep(0.01)  # Simulate some work
        return 'Hello from Demo App! This request was counted.\n'
    
    @app.route('/api')
    def api():
        request_counter.labels(service='frontend', endpoint='/api').inc()
        time.sleep(0.02)
        return 'API response\n'
    
    @app.route('/metrics')
    def metrics():
        return Response(generate_latest(REGISTRY), mimetype='text/plain')
    
    @app.route('/health')
    def health():
        return 'OK\n'
    
    if __name__ == '__main__':
        app.run(host='0.0.0.0', port=8080)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: app
        image: python:3.11-slim
        command: ["/bin/sh", "-c"]
        args:
          - |
            pip install flask prometheus-client
            python /app/app.py
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: app-code
          mountPath: /app
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
      volumes:
      - name: app-code
        configMap:
          name: demo-app-code
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: frontend
